#include "FortItemCard_PowerRatingBlock_PersonnelAndSchematics_Configuration.h"

FFortItemCard_PowerRatingBlock_PersonnelAndSchematics_Configuration::FFortItemCard_PowerRatingBlock_PersonnelAndSchematics_Configuration() {
}

