#include "FortPlayerSurveyButtonListMultipleSelectionAnswerWidgetBaseInternalButtonData.h"

FFortPlayerSurveyButtonListMultipleSelectionAnswerWidgetBaseInternalButtonData::FFortPlayerSurveyButtonListMultipleSelectionAnswerWidgetBaseInternalButtonData() {
    this->ButtonWidget = NULL;
}

