#pragma once
#include "CoreMinimal.h"
#include "EFortUIFeature.generated.h"

UENUM(BlueprintType)
enum class EFortUIFeature : uint8 {
    ShowHome,
    ShowPlay,
    ShowCommand,
    ShowHeros,
    ShowSquads,
    ShowArmory,
    ShowLocker,
    ShowSkillTree,
    ShowStore,
    ShowQuests,
    ShowMainStore,
    ShowContextHelpMenu,
    ShowCampaign,
    ShowActiveBoost,
    ShowJournal,
    ShowPartyBar,
    ShowChatWindow,
    ShowFriendsMenu,
    ShowObjectives,
    ShowRatingIconsInTopbar,
    ShowAntiAddictionMessage,
    ShowMinorShutdownMessage,
    ShowHealthWarningScreen,
    ShowSimplifiedHUD,
    LargeHeaderFooterButtons,
    ShowAthenaFavoriting,
    ShowAthenaItemRandomization,
    ShowAthenaChallenges,
    ShowBattlePass,
    ShowBattlePassFAQ,
    ShowReplays,
    ShowProfileStatsUI,
    ShowAthenaItemShop,
    ShowShowdown,
    ShowAccountBoosts,
    ShowCustomerSupport,
    ShowGlobalChat,
    ShowEULA,
    ShowEndOfZoneCinematic,
    ShowOnboardingCinematics,
    ShowFounderBannerIcons,
    ShowCurrentRegionInLobby,
    ShowPrerollLlamas,
    EnableFoundersDailyRewards,
    EnableTwitchIntegration,
    EnableMatchmakingRegionSetting,
    EnableLanguageSetting,
    EnableFriendCodeSetting,
    EnableEarlyAccessLoadingScreenBanner,
    EnableAlterationModifications,
    EnableSchematicRarityUpgrade,
    EnableMissionActivationVote,
    EnableLtmRetrieveTheData,
    EnableUpgradesVideos,
    Max_None,
};

