#pragma once

#include "CoreMinimal.h"

UENUM()
enum class EIndicatorStateImage : uint8 
{
	Default,
	InCombat,
	DBNO,
	BeingRevived,
	Dead,
	LAST_FRIENDLY_STATE,
	FIRST_CHAT_MESSAGE,
	NeedAmmoHeavy,
	NeedAmmoLight,
	NeedAmmoMedium,
	NeedAmmoShells,
	NeedAmmoRocket,
	ChatBubble,
	EnemySpotted,
	NeedBandages,
	NeedMaterials,
	NeedShields,
	NeedWeapon,
	LAST_CHAT_MESSAGE,
	FIRST_MATE_STATE,
	Squadmate,
	Teammate,
	LAST_MATE_STATE,
	FIRST_ENEMY_STATE,
	Enemy,
	LAST_ENEMY_STATE,
	FIRST_NPC_STATE,
	FriendlyNPC,
	EnemyNPC,
	EliteFriendlyNPC,
	EliteEnemyNPC,
	LAST_NPC_STATE,
	FIRST_WORLDITEM_STATE,
	Interactable,
	InteractableLarge,
	GameplayItem,
	TreasureChest,
	LAST_WORLDITEM_STATE,
	FIRST_HARDCORE_STATE,
	HardCoreBeacon,
	LAST_HARDCORE_STATE,
	LAST_STATE,
	None,
	MAX,
};
