#include "FortAIHotSpotSlot.h"

UFortAIHotSpotSlot::UFortAIHotSpotSlot() {
    SlotType = EFortHotSpotSlot::Melee;
    bHasProjectedLocation = false;
    bProjectedOnLowArea = false;
    bIsAutoGenerated = false;
    bCanDuplicateOnProjection = true;
    bCanProjectUp = true;
}

