#pragma once
#include "CoreMinimal.h"
#include "EFortInputActionGroup.generated.h"

UENUM(BlueprintType)
enum class EFortInputActionGroup : uint8 {
    AllModes,
    Combat,
    Building,
    Movement,
    Edit,
    Death,
    Cinematic,
    Picker,
    Other,
    Interaction,
    ShoppingCart,
    ShoppingCartDriver,
    ShoppingCartPassenger,
    Cannon,
    CannonDriver,
    CannonPassenger,
    GolfCart,
    GolfCartDriver,
    GolfCartPassenger,
    QuadCrasher,
    QuadCrasherDriver,
    QuadCrasherPassenger,
    Biplane,
    BiplaneDriver,
    BiplanePassenger,
    Hamsterball,
    Jackal,
    Ostrich,
    OstrichDriver,
    OstrichPassenger,
    Meatball,
    MeatballDriver,
    MeatballPassenger,
    HoagieDriver,
    Dagwood,
    DagwoodDriver,
    DagwoodPassenger,
    MountedTurret,
    Spectating,
    FullscreenMap,
    CreativeAll,
    CreativeMoveToolEquipped,
    CreativeMoveObjectsFreely,
    CreativeMoveBuildingsOnGrid,
    CreativeFlying,
    CreativeIslandPanel,
    PropSelectorEquipped,
    DBNOCarryStart,
    DBNOCarryStop,
    DBNOCarry,
    InteractionStart,
    InteractionStop,
    BattleLab,
    SuperDuper,
    Tether,
    CombatAndBuilding,
};

