#pragma once
#include "CoreMinimal.h"
#include "EFortContextualTutorialTypes.generated.h"

UENUM(BlueprintType)
enum class EFortContextualTutorialTypes : uint8 {
    AllSeen,
    BattleBus,
    BattleBusMobile,
    Skydiving,
    Landing,
    NearbyChest,
    NearbyChestMobile,
    NearbyLootPC,
    NearbyLootMobile,
    Harvest,
    WeakSpot,
    UseSmallShieldPotion,
    UseShieldPotion,
    UseSlurpJuice,
    UseChugJug,
    UseBandage,
    UseMedKit,
    StormForming,
    StormFormingMobile,
    EquipWeapon,
    EquipWeaponMobile,
    MarkLocation,
    MarkEnemy,
    Welcome,
    PrepareToJump,
    ShieldBlazer,
    ChugSplash,
    LandNearPoi,
    UseSmallShieldPotionInformative,
    UseShieldPotionInformative,
    UseSlurpJuiceInformative,
    UseBandageInformative,
    UseMedKitInformative,
    ChugSplashInformative,
    NearHideableObject,
    NearUpgradeBench,
    HealBazooka,
    FishingFishSmallFry,
    FishingFishFlopper,
    FishingFishSlurpfish,
    FishingCan,
    FishingTrophy,
    NearUpgradeBenchWithMaterial,
    NearFactionChange,
    NearObjectFactionScanner,
    ThrownConsumable,
    BiplaneRoll,
    Fly,
    WhirlpoolGeyser,
    CampfireSuccess,
    CampfireFail,
    UpgradeBenchSidegrade,
    VehicleValetCar,
    VehicleValetLowFuel,
    VehicleValetGasCan,
    VehicleValetGasPump,
    Count,
    None,
};

