#pragma once
#include "CoreMinimal.h"
#include "EFrontEndCamera.generated.h"

UENUM(BlueprintType)
enum class EFrontEndCamera : uint8 {
    Invalid,
    Command,
    Command_HeroLoadout,
    LegacyHeroLoadout,
    Cosmetics,
    Expeditions,
    FrontendDefault,
    Heroes,
    HeroSelect,
    HeroLoadout,
    Home,
    HomeBase,
    Login,
    Manage1,
    Manage2,
    Manage3,
    Manage4,
    MissionControl,
    Party,
    Play,
    Research,
    SkillTrees,
    SmallCosmetics,
    SpatialUI,
    SpecialEvent,
    SpecialEvent2,
    SpecialEvent3,
    Store,
    StoreItemInspect,
    StwFrontendDefault,
    SurvivorSquadBuilding1,
    SurvivorSquadBuilding2,
    SurvivorSquadBuilding3,
    SurvivorSquadBuilding4,
    TutorialPhaseOne,
    TutorialPhaseTwo,
    TutorialPhaseThree,
    Upgrades,
    Vault,
    WorldMap,
    LobbyCentered,
    CosmeticDisplay,
    BattlePass,
    Rewards,
    SpecialEventRewards,
    Armory,
};

