#pragma once
#include "CoreMinimal.h"
#include "EIndicatorStateImage.generated.h"

UENUM(BlueprintType)
enum class EIndicatorStateImage : uint8 {
    FIRST_FRIENDLY_STATE,
    Default = 0x0,
    InCombat,
    DBNO,
    BeingRevived,
    Dead,
    LAST_FRIENDLY_STATE = 0x4,
    FIRST_CHAT_MESSAGE,
    NeedAmmoHeavy = 0x5,
    NeedAmmoLight,
    NeedAmmoMedium,
    NeedAmmoShells,
    NeedAmmoRocket,
    ChatBubble,
    EnemySpotted,
    NeedBandages,
    NeedMaterials,
    NeedShields,
    NeedWeapon,
    LAST_CHAT_MESSAGE = 0xF,
    FIRST_MATE_STATE,
    Squadmate = 0x10,
    Teammate,
    LAST_MATE_STATE = 0x11,
    FIRST_ENEMY_STATE,
    Enemy = 0x12,
    LAST_ENEMY_STATE = 0x12,
    FIRST_NPC_STATE,
    FriendlyNPC = 0x13,
    EnemyNPC,
    EliteFriendlyNPC,
    EliteEnemyNPC,
    LAST_NPC_STATE = 0x16,
    FIRST_WORLDITEM_STATE,
    Interactable = 0x17,
    InteractableLarge,
    GameplayItem,
    TreasureChest,
    LAST_WORLDITEM_STATE = 0x1A,
    FIRST_HARDCORE_STATE,
    HardCoreBeacon = 0x1B,
    LAST_HARDCORE_STATE = 0x1B,
    LAST_STATE = 0x1B,
    None,
    MAX,
};

