#pragma once
#include "CoreMinimal.h"
#include "AIHotSpotSlot.h"
#include "EFortHotSpotSlot.h"
#include "FortAIHotSpotSlot.generated.h"

UCLASS(Blueprintable, EditInlineNew)
class UFortAIHotSpotSlot : public UAIHotSpotSlot {
    GENERATED_BODY()
public:
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    EFortHotSpotSlot SlotType;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    uint8 bHasProjectedLocation: 1;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    uint8 bProjectedOnLowArea: 1;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    uint8 bIsAutoGenerated: 1;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    uint8 bCanDuplicateOnProjection: 1;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    uint8 bCanProjectUp: 1;
    
    UFortAIHotSpotSlot();
};

